image: docker:stable

stages:
  - build_bdd_centrale
  - test_mount
  - build_neo4j_CSV
  - build_neo4j_database
  - build_docker_image
  - deploy

variables:
  GIT_DEPTH: "1"
  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/neo4j_toflit18:$CI_COMMIT_REF_SLUG"
  SHARED_FOLDER: "/builds/$CI_PROJECT_NAME/"

build_bdd_centrale:
  stage: build_bdd_centrale
  tags:
    - proxy
  artifacts:
    untracked: true
    expire_in: "1 day"
    exclude:
      - "__pycache__"
  image: python:3.7-alpine3.9
  script:
    - cd ./scripts/ && python aggregate_sources_in_bdd_centrale_with_calculations.py
  only:
    - new_import
    - staging
    - prod

test_mount:
  stage: test_mount
  tags:
    - proxy
  artifacts:
    untracked: true
  script:
    - export JOB_CONTAINER_ID=`docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID"`
    - echo $JOB_CONTAINER_ID
    - export MOUNT_NAME=$(docker inspect $CONTAINER_ID -f "{{ range .Mounts }}{{ if eq .Destination \"/builds/${CI_PROJECT_NAMESPACE}\" }}{{ .Source }}{{end}}{{end}}" | cut -d "/" -f 6)
    - echo $MOUNT_NAME
    - echo $CI_PROJECT_NAME
    - echo "hello World" > ${SHARED_FOLDER}/coucou.txt
    - ls -la ${SHARED_FOLDER}
    # test mount methods
    - docker run --rm -v $MOUNT_NAME:/builds -w ${SHARED_FOLDER} docker:stable ls -la
    - docker run --rm --volumes-from ${JOB_CONTAINER_ID} -w ${SHARED_FOLDER}  docker:stable cat coucou.txt
    - docker run --rm --volume=${CI_PROJECT_DIR}:/data/ -w /data/neo4j_database  docker:stable ls -la
  only:
    - new_import

neo4j_CSV:
  stage: build_neo4j_CSV
  tags:
    - proxy
  artifacts:
    untracked: true
    expire_in: "1 day"
  dependencies:
    - build_bdd_centrale
  image: node:7.9.0-alpine
  script:
    - apk add --no-cache git
    - mkdir -p neo4j_import
    - cd $CI_PROJECT_DIR/scripts/neo4j && npm i
    - cd $CI_PROJECT_DIR/scripts/neo4j && npm run import -- -- --path $CI_PROJECT_DIR --output $CI_PROJECT_DIR/neo4j_import/
  only:
    - new_import
    - staging
    - prod

neo4j_database:
  stage: build_neo4j_database
  tags:
    - proxy
  artifacts:
    untracked: true
    expire_in: "1 day"
  dependencies:
    - neo4j_CSV
  image: neo4j:3.5.16
  script:
    - mkdir -p neo4j_data/databases
    # import CSV to neo4j
    - /var/lib/neo4j/bin/neo4j-admin import --database toflit18.db --nodes $CI_PROJECT_DIR/neo4j_import/nodes.csv --relationships $CI_PROJECT_DIR/neo4j_import/edges.csv
    - mv /var/lib/neo4j/data/databases/toflit18.db $CI_PROJECT_DIR/neo4j_data/databases/graph.db
  only:
    - new_import
    - staging
    - prod

build_docker_image:
  stage: build_docker_image
  tags:
    - proxy
  dependencies:
    - neo4j_database
  script:
    - export CI_BUILD_NETWORK_ID="$HOSTNAME-job-$CI_JOB_ID-network"
    - export JOB_CONTAINER_ID=`docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID"`
    - apk add --no-cache npm bash curl
    - npm install -g n
    - n 7.9
    - cp -R ${CI_PROJECT_DIR}/neo4j_data ${SHARED_FOLDER}/
    - chown -R 101:101 ${SHARED_FOLDER}/neo4j_data
    - ls -lah ${SHARED_FOLDER}/neo4j_data
    - ls -lah ${SHARED_FOLDER}/neo4j_data/databases/graph.db
    # start neo4j with the DB created in previous step
    - docker rm neo4j_build
    - docker run --name neo4j_build  --volumes-from ${JOB_CONTAINER_ID} --env "dbms_directories_data=${SHARED_FOLDER}/neo4j_data" --network=$CI_BUILD_NETWORK_ID -p 7687:7687 --env "dbms_connectors_default_listen_address=0.0.0.0" --env "NEO4J_dbms_memory_heap_max__size=2048M" --env "NEO4J_dbms_memory_pagecache_size=2048M" --env "NEO4J_dbms_transaction_timeout=180s" --env "NEO4J_AUTH=neo4j/admin" neo4j:3.5.16 > neo4j_build.log &
    - sleep 5
    - ls -lah ${SHARED_FOLDER}/neo4j_data
    - ls -lah ${SHARED_FOLDER}/neo4j_data/databases/graph.db
    - cat neo4j_build.log
    - cat /neo4j_logs/*.log
    - docker logs neo4j_build
    - curl -i neo4j_build:7687
    # run quantities and indices scripts
    - cd ${CI_PROJECT_DIR}/scripts/neo4j
    - npm run quantities -- -- --path $CI_PROJECT_DIR
    - npm run indices
    # stop neo4j
    - docker stop neo4j_build
    - rm -rf ${CI_PROJECT_DIR}/neo4j_data/*
    - cp -R ${SHARED_FOLDER}/neo4j_data/* ${CI_PROJECT_DIR}/neo4j_data/
    # build image
    - cd $CI_PROJECT_DIR
    - docker build -t $DOCKER_IMAGE_NAME -f Dockerfile .
    # push
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCKER_IMAGE_NAME
    - docker logs neo4j_build
    - docker rm neo4j_build
  variables:
    FF_NETWORK_PER_BUILD: "true"
    DOCKER_TLS_CERTDIR: ""
    NEO4J_USER: "neo4j"
    NEO4J_PASSWORD: "admin"
    NEO4J_HOST: "neo4j_build"
    NEO4J_PORT: "7687"
  only:
    - new_import
    - staging
    - prod

deploy:
  image:
    name: jrisp/kubehelper:latest
    entrypoint: [""]
  stage: deploy
  tags:
    - proxy
  dependencies:
    - build_docker_image
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --certificate-authority="$KUBE_CA_PEM_FILE"
    - kubectl config set-credentials gitlab-admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=gitlab-admin
    - kubectl config use-context default
    - kubectl -n toflit18 rollout restart deployment toflit18-db
    - kubectl -n toflit18 rollout restart deployment toflit18-api
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - staging
    - prod
