import os
import itertools

absolute_path=os.getcwd()

for (dirpath,dirnames,filenames) in os.walk("sources"):

	filenames=[f for f in filenames if "_v" in f] 
	if len(filenames)>0:
		target_directory=dirpath
		versions=[(f.split(".")[0].split("_v")[-1],f,f.split(".")[0].split("_v")[0]) for f in filenames]
		versions.sort(key=lambda t:t[2])
		print """cd "%s";"""%os.path.join(absolute_path,target_directory)
		#print versions
		for file, versions in itertools.groupby(versions,lambda t:t[2]) :
			
			versions=list(versions)
			versions.sort(key=lambda t:int(t[0]))

			for v,filename,new_filename in versions :
				
				print "cp %s %s.csv;"%(filename,new_filename)
				print "git rm %s;"%filename
				print "git add %s.csv"%new_filename
				print """git commit %s.csv -m "version %s for %s - commit generated by %s" ;"""%(new_filename,v,new_filename,"scripts/merge_versions_in_git_1.sh")
				if int(v)>=20:
					print """echo "%s.csv" >> %s"""%(os.path.join(target_directory,new_filename),os.path.join(absolute_path,"sources","v20_files.txt"))