import os
import itertools

for (dirpath,dirnames,filenames) in os.walk("../sources"):

	filenames=[f for f in filenames if "_v" in f] 
	if len(filenames)>1:
		target_directory=dirpath
		versions=[(f.split(".")[0].split("_v")[-1],f,f.split(".")[0].split("_v")[0]) for f in filenames]
		versions.sort(key=lambda t:t[2])
		print "cd %s;"%target_directory
		#print versions
		for file, versions in itertools.groupby(versions,lambda t:t[2]) :
			
			versions=list(versions)
			versions.sort(key=lambda t:int(t[0]))

			for v,filename,new_filename in versions :
				
				print "mv %s %s.csv;"%(filename,new_filename)
				print """git commit %s.csv -m "version %s for %s - commit generated by %s" ;"""%(new_filename,v,new_filename,"scripts/merge_versions_in_git_1.sh")