cd "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises";
cp bdd_marchandises_classifiees_v3.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v3.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 3 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v6.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v6.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 6 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v7.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v7.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 7 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v8.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v8.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 8 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v9.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v9.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 9 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v10.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v10.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 10 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v11.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v11.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 11 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v15.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v15.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 15 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v16.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v16.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 16 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v18.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v18.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 18 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v19.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v19.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 19 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_classifiees_v21.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v21.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 21 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_classifiees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_classifiees_v22.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v22.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 22 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_classifiees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_classifiees_v23.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v23.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 23 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_classifiees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_classifiees_v24.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v24.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 24 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_classifiees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_classifiees_v30.csv bdd_marchandises_classifiees.csv;
git rm bdd_marchandises_classifiees_v30.csv;
git add bdd_marchandises_classifiees.csv
git commit bdd_marchandises_classifiees.csv -m "version 30 for bdd_marchandises_classifiees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_classifiees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_classifiées_v14.csv bdd_marchandises_classifiées.csv;
git rm bdd_marchandises_classifiées_v14.csv;
git add bdd_marchandises_classifiées.csv
git commit bdd_marchandises_classifiées.csv -m "version 14 for bdd_marchandises_classifiées - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v2.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v2.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 2 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v5.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v5.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 5 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v8.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v8.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 8 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v9.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v9.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 9 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v10.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v10.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 10 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v11.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v11.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 11 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v12.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v12.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 12 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v13.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v13.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 13 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v14.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v14.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 14 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v19.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v19.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 19 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
cp bdd_marchandises_normalisees_v20.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v20.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 20 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v21.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v21.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 21 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v22.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v22.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 22 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v23.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v23.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 23 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v26.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v26.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 26 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v27.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v27.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 27 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v28.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v28.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 28 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
cp bdd_marchandises_normalisees_v33.csv bdd_marchandises_normalisees.csv;
git rm bdd_marchandises_normalisees_v33.csv;
git add bdd_marchandises_normalisees.csv
git commit bdd_marchandises_normalisees.csv -m "version 33 for bdd_marchandises_normalisees - commit generated by ./merge_traitement_marchandises_versions.sh" ;
echo "/home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/bdd_marchandises_normalisees.csv" >> /home/pgi/Documents/expe/toflit18_data/Traitement des marchandises/v20_files.txt
