cd "/home/pgi/Documents/expe/toflit18_data/sources/Local/Montpellier";
cp Années_1730_v1.csv Années_1730.csv;
git rm Années_1730_v1.csv;
git add Années_1730.csv
git commit Années_1730.csv -m "version 1 for Années_1730 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Tableau Général";
cp Tableau Général_v20.csv Tableau Général.csv;
git rm Tableau Général_v20.csv;
git add Tableau Général.csv
git commit Tableau Général.csv -m "version 20 for Tableau Général - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Tableau Général/Tableau Général.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/Divers/AN/F_12_1834A";
cp 1671_v1.csv 1671.csv;
git rm 1671_v1.csv;
git add 1671.csv
git commit 1671.csv -m "version 1 for 1671 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cd "/home/pgi/Documents/expe/toflit18_data/sources/National par direction/Saint-Brieuc";
cp 1750_v20.csv 1750.csv;
git rm 1750_v20.csv;
git add 1750.csv
git commit 1750.csv -m "version 20 for 1750 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National par direction/Saint-Brieuc/1750.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National par direction/AN/F_12_1666 et 1667";
cp 1789_v20.csv 1789.csv;
git rm 1789_v20.csv;
git add 1789.csv
git commit 1789.csv -m "version 20 for 1789 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National par direction/AN/F_12_1666 et 1667/1789.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
