cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Résumé/AN/F_12_251";
cp 1787_v1.csv 1787.csv;
git rm 1787_v1.csv;
git add 1787.csv
git commit 1787.csv -m "version 1 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1787_v2.csv 1787.csv;
git rm 1787_v2.csv;
git add 1787.csv
git commit 1787.csv -m "version 2 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1787_v20.csv 1787.csv;
git rm 1787_v20.csv;
git add 1787.csv
git commit 1787.csv -m "version 20 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Résumé/AN/F_12_251/1787.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1788_v1.csv 1788.csv;
git rm 1788_v1.csv;
git add 1788.csv
git commit 1788.csv -m "version 1 for 1788 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1788_v2.csv 1788.csv;
git rm 1788_v2.csv;
git add 1788.csv
git commit 1788.csv -m "version 2 for 1788 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1788_v3.csv 1788.csv;
git rm 1788_v3.csv;
git add 1788.csv
git commit 1788.csv -m "version 3 for 1788 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1788_v20.csv 1788.csv;
git rm 1788_v20.csv;
git add 1788.csv
git commit 1788.csv -m "version 20 for 1788 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Résumé/AN/F_12_251/1788.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1789_v1.csv 1789.csv;
git rm 1789_v1.csv;
git add 1789.csv
git commit 1789.csv -m "version 1 for 1789 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1789_v2.csv 1789.csv;
git rm 1789_v2.csv;
git add 1789.csv
git commit 1789.csv -m "version 2 for 1789 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1789_v20.csv 1789.csv;
git rm 1789_v20.csv;
git add 1789.csv
git commit 1789.csv -m "version 20 for 1789 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Résumé/AN/F_12_251/1789.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_245_1777";
cp 1777_v1.csv 1777.csv;
git rm 1777_v1.csv;
git add 1777.csv
git commit 1777.csv -m "version 1 for 1777 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1777_v2.csv 1777.csv;
git rm 1777_v2.csv;
git add 1777.csv
git commit 1777.csv -m "version 2 for 1777 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1777_v20.csv 1777.csv;
git rm 1777_v20.csv;
git add 1777.csv
git commit 1777.csv -m "version 20 for 1777 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_245_1777/1777.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_243_1776";
cp 1776_v1.csv 1776.csv;
git rm 1776_v1.csv;
git add 1776.csv
git commit 1776.csv -m "version 1 for 1776 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1776_v2.csv 1776.csv;
git rm 1776_v2.csv;
git add 1776.csv
git commit 1776.csv -m "version 2 for 1776 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1776_v20.csv 1776.csv;
git rm 1776_v20.csv;
git add 1776.csv
git commit 1776.csv -m "version 20 for 1776 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_243_1776/1776.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_248_1780";
cp 1780_v1.csv 1780.csv;
git rm 1780_v1.csv;
git add 1780.csv
git commit 1780.csv -m "version 1 for 1780 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1780_v2.csv 1780.csv;
git rm 1780_v2.csv;
git add 1780.csv
git commit 1780.csv -m "version 2 for 1780 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1780_v20.csv 1780.csv;
git rm 1780_v20.csv;
git add 1780.csv
git commit 1780.csv -m "version 20 for 1780 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_248_1780/1780.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_246_1778";
cp 1778_v1.csv 1778.csv;
git rm 1778_v1.csv;
git add 1778.csv
git commit 1778.csv -m "version 1 for 1778 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1778_v20.csv 1778.csv;
git rm 1778_v20.csv;
git add 1778.csv
git commit 1778.csv -m "version 20 for 1778 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_246_1778/1778.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_250_1787";
cp 1787_v1.csv 1787.csv;
git rm 1787_v1.csv;
git add 1787.csv
git commit 1787.csv -m "version 1 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1787_v2.csv 1787.csv;
git rm 1787_v2.csv;
git add 1787.csv
git commit 1787.csv -m "version 2 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1787_v20.csv 1787.csv;
git rm 1787_v20.csv;
git add 1787.csv
git commit 1787.csv -m "version 20 for 1787 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_250_1787/1787.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_242_1775";
cp 1775_v1.csv 1775.csv;
git rm 1775_v1.csv;
git add 1775.csv
git commit 1775.csv -m "version 1 for 1775 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1775_v2.csv 1775.csv;
git rm 1775_v2.csv;
git add 1775.csv
git commit 1775.csv -m "version 2 for 1775 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1775_v20.csv 1775.csv;
git rm 1775_v20.csv;
git add 1775.csv
git commit 1775.csv -m "version 20 for 1775 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_242_1775/1775.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/AN Paris/F_12_249bis_1782";
cp 1782_v1.csv 1782.csv;
git rm 1782_v1.csv;
git add 1782.csv
git commit 1782.csv -m "version 1 for 1782 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1782_v2.csv 1782.csv;
git rm 1782_v2.csv;
git add 1782.csv
git commit 1782.csv -m "version 2 for 1782 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1782_v20.csv 1782.csv;
git rm 1782_v20.csv;
git add 1782.csv
git commit 1782.csv -m "version 20 for 1782 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/AN Paris/F_12_249bis_1782/1782.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/IIHS - Amsterdam";
cp 1767_v2.csv 1767.csv;
git rm 1767_v2.csv;
git add 1767.csv
git commit 1767.csv -m "version 2 for 1767 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1767_v20.csv 1767.csv;
git rm 1767_v20.csv;
git add 1767.csv
git commit 1767.csv -m "version 20 for 1767 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/IIHS - Amsterdam/1767.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1769_v1.csv 1769.csv;
git rm 1769_v1.csv;
git add 1769.csv
git commit 1769.csv -m "version 1 for 1769 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1769_v2.csv 1769.csv;
git rm 1769_v2.csv;
git add 1769.csv
git commit 1769.csv -m "version 2 for 1769 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1769_v20.csv 1769.csv;
git rm 1769_v20.csv;
git add 1769.csv
git commit 1769.csv -m "version 20 for 1769 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/IIHS - Amsterdam/1769.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1771_v1.csv 1771.csv;
git rm 1771_v1.csv;
git add 1771.csv
git commit 1771.csv -m "version 1 for 1771 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1771_v2.csv 1771.csv;
git rm 1771_v2.csv;
git add 1771.csv
git commit 1771.csv -m "version 2 for 1771 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1771_v20.csv 1771.csv;
git rm 1771_v20.csv;
git add 1771.csv
git commit 1771.csv -m "version 20 for 1771 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/IIHS - Amsterdam/1771.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1774_v1.csv 1774.csv;
git rm 1774_v1.csv;
git add 1774.csv
git commit 1774.csv -m "version 1 for 1774 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1774_v2.csv 1774.csv;
git rm 1774_v2.csv;
git add 1774.csv
git commit 1774.csv -m "version 2 for 1774 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1774_v20.csv 1774.csv;
git rm 1774_v20.csv;
git add 1774.csv
git commit 1774.csv -m "version 20 for 1774 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/IIHS - Amsterdam/1774.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1774_v21.csv 1774.csv;
git rm 1774_v21.csv;
git add 1774.csv
git commit 1774.csv -m "version 21 for 1774 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/IIHS - Amsterdam/1774.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/MS Montbret 155-2";
cp 1759_v1.csv 1759.csv;
git rm 1759_v1.csv;
git add 1759.csv
git commit 1759.csv -m "version 1 for 1759 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1759_v2.csv 1759.csv;
git rm 1759_v2.csv;
git add 1759.csv
git commit 1759.csv -m "version 2 for 1759 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1759_v20.csv 1759.csv;
git rm 1759_v20.csv;
git add 1759.csv
git commit 1759.csv -m "version 20 for 1759 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/MS Montbret 155-2/1759.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 849";
cp 1752_v1.csv 1752.csv;
git rm 1752_v1.csv;
git add 1752.csv
git commit 1752.csv -m "version 1 for 1752 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1752_v2.csv 1752.csv;
git rm 1752_v2.csv;
git add 1752.csv
git commit 1752.csv -m "version 2 for 1752 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1752_v20.csv 1752.csv;
git rm 1752_v20.csv;
git add 1752.csv
git commit 1752.csv -m "version 20 for 1752 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 849/1752.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1772_v1.csv 1772.csv;
git rm 1772_v1.csv;
git add 1772.csv
git commit 1772.csv -m "version 1 for 1772 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1772_v2.csv 1772.csv;
git rm 1772_v2.csv;
git add 1772.csv
git commit 1772.csv -m "version 2 for 1772 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1772_v20.csv 1772.csv;
git rm 1772_v20.csv;
git add 1772.csv
git commit 1772.csv -m "version 20 for 1772 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 849/1772.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cd "/home/pgi/Documents/expe/toflit18_data/sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1";
cp 1754_v1.csv 1754.csv;
git rm 1754_v1.csv;
git add 1754.csv
git commit 1754.csv -m "version 1 for 1754 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1754_v2.csv 1754.csv;
git rm 1754_v2.csv;
git add 1754.csv
git commit 1754.csv -m "version 2 for 1754 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1754_v3.csv 1754.csv;
git rm 1754_v3.csv;
git add 1754.csv
git commit 1754.csv -m "version 3 for 1754 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1754_v20.csv 1754.csv;
git rm 1754_v20.csv;
git add 1754.csv
git commit 1754.csv -m "version 20 for 1754 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1/1754.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1755_v1.csv 1755.csv;
git rm 1755_v1.csv;
git add 1755.csv
git commit 1755.csv -m "version 1 for 1755 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1755_v2.csv 1755.csv;
git rm 1755_v2.csv;
git add 1755.csv
git commit 1755.csv -m "version 2 for 1755 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1755_v3.csv 1755.csv;
git rm 1755_v3.csv;
git add 1755.csv
git commit 1755.csv -m "version 3 for 1755 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1755_v20.csv 1755.csv;
git rm 1755_v20.csv;
git add 1755.csv
git commit 1755.csv -m "version 20 for 1755 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1/1755.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1755_v21.csv 1755.csv;
git rm 1755_v21.csv;
git add 1755.csv
git commit 1755.csv -m "version 21 for 1755 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1/1755.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1757_v1.csv 1757.csv;
git rm 1757_v1.csv;
git add 1757.csv
git commit 1757.csv -m "version 1 for 1757 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1757_v2.csv 1757.csv;
git rm 1757_v2.csv;
git add 1757.csv
git commit 1757.csv -m "version 2 for 1757 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1757_v20.csv 1757.csv;
git rm 1757_v20.csv;
git add 1757.csv
git commit 1757.csv -m "version 20 for 1757 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1/1757.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
cp 1761_v1.csv 1761.csv;
git rm 1761_v1.csv;
git add 1761.csv
git commit 1761.csv -m "version 1 for 1761 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1761_v2.csv 1761.csv;
git rm 1761_v2.csv;
git add 1761.csv
git commit 1761.csv -m "version 2 for 1761 - commit generated by scripts/merge_versions_in_git_1.sh" ;
cp 1761_v20.csv 1761.csv;
git rm 1761_v20.csv;
git add 1761.csv
git commit 1761.csv -m "version 20 for 1761 - commit generated by scripts/merge_versions_in_git_1.sh" ;
echo "sources/National/Objet Général/Rouen/Bibliothèque Municipale Rouen/Ms Montbret 155-1/1761.csv" >> /home/pgi/Documents/expe/toflit18_data/sources/v20_files.txt
