cd "/home/pgi/Documents/expe/toflit18_data/base_centrale/";
cp bdd_centrale_v1.csv bdd_centrale.csv;
git rm bdd_centrale_v1.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 1 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v2.csv bdd_centrale.csv;
git rm bdd_centrale_v2.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 2 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v3.csv bdd_centrale.csv;
git rm bdd_centrale_v3.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 3 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v4.csv bdd_centrale.csv;
git rm bdd_centrale_v4.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 4 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v5.csv bdd_centrale.csv;
git rm bdd_centrale_v5.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 5 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v6.csv bdd_centrale.csv;
git rm bdd_centrale_v6.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 6 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v7.csv bdd_centrale.csv;
git rm bdd_centrale_v7.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 7 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v8.csv bdd_centrale.csv;
git rm bdd_centrale_v8.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 8 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v9.csv bdd_centrale.csv;
git rm bdd_centrale_v9.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 9 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v10.csv bdd_centrale.csv;
git rm bdd_centrale_v10.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 10 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v11.csv bdd_centrale.csv;
git rm bdd_centrale_v11.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 11 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v12.csv bdd_centrale.csv;
git rm bdd_centrale_v12.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 12 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v13.csv bdd_centrale.csv;
git rm bdd_centrale_v13.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 13 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v14.csv bdd_centrale.csv;
git rm bdd_centrale_v14.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 14 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v15.csv bdd_centrale.csv;
git rm bdd_centrale_v15.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 15 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v16.csv bdd_centrale.csv;
git rm bdd_centrale_v16.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 16 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v17.csv bdd_centrale.csv;
git rm bdd_centrale_v17.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 17 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v18.csv bdd_centrale.csv;
git rm bdd_centrale_v18.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 18 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v19.csv bdd_centrale.csv;
git rm bdd_centrale_v19.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 19 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
cp bdd_centrale_v20.csv bdd_centrale.csv;
git rm bdd_centrale_v20.csv;
git add bdd_centrale.csv
git commit bdd_centrale.csv -m "version 20 for bdd_centrale - commit generated by generate_merge_versions_in_git_script.py" ;
echo "base_centrale/bdd_centrale.csv" >> /home/pgi/Documents/expe/toflit18_data/base_centrale/v20_files.txt

